### ISSUE TITLE
Prividing the software through package managers

### ISSUE THREAD

**Issue by Foadsf** [rdbyk/balisc#835]
First of all I should say that I'm very interested in this project. With the Scilab community so fragmented and Scilab key members avoiding modern platforms like GitHub, I think Balisc can be a way out. However trying to search the software on [Repology ](https://repology.org/projects/?search=balisc&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=) brings no results and that's a little bit depressing. I was wondering if the Balisc team could dedicate some time to take care of some major package managers ASAP. First of all it would be great to focus on distro agnostic (aka cross-distro) package managers like LinuxBrew / macBrew , EasyBuild, Spack, AppImage... If you provide macBrew formula theoretically it should also be compatible on LinuxBrew. On Windows Chocolatey could be the best choice. So in general my suggestion target these two:

 * LinuxBrew / macBrew
 * Chocolatey

**Comment by rdbyk** [comment]
First of all, let me say, that we really appreciate your interest in Balisc. This is a very experimental
project and its team is currently really small :wink:, thus we try to put our focus on one platform (Linux)
and one build environment (autoconf/make/gcc).
Nevertheless, it should be feasible for someone to give it a try under MacOS. Regarding Windows, we have dropped the MSVC (Visual Studio) build system, it is just to much effort to maintain it ... even without it, the Scilab/Balisc code base is hard to maintain and there are really a lot of serious bugs and rough edges, which should be fixed first ...
However, any contribution (issues, pull requests) to improve things is highly welcome.
 I will close this issue for now, because I don't think it will resolved in a foreseeable period of time.
Thanks for your input!

**Comment by Foadsf** [comment]
Dear @rdbyk thanks for the reply. Considering that you are are targeting Linux, I would suggest to package Balisc for LinuxBrew. benefits:

 * it is both Linux and mac
 * cross distro
 * compiling from source
